[platformio]
default_envs = nanoatmega328

[env]
build_flags = 
    -Wall
    -Wextra

# ---------- ARDUINO (сборка примера) ----------
[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 9600
; Где лежит пример
src_dir = examples/arduino_basic/src
; Подключаем корень библиотеки, чтобы MELT_MT24S2A.cpp скомпилировался
lib_deps = symlink://.

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
src_dir = examples/arduino_basic/src
lib_deps = symlink://.

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
src_dir = examples/arduino_basic/src
lib_deps = symlink://.

# ---------- STM32 (пример) ----------
[env:stm32_nucleo]
platform = ststm32
board = nucleo_f103rb
framework = arduino
src_dir = examples/arduino_basic/src
lib_deps = symlink://.
monitor_speed = 115200

[env:stm32_bluepill]
platform = ststm32
board = bluepill_f103c8
framework = arduino
src_dir = examples/arduino_basic/src
lib_deps = symlink://.
upload_protocol = stlink
monitor_speed = 115200

# ---------- ESP (пример) ----------
[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
src_dir = examples/arduino_basic/src
lib_deps = symlink://.
monitor_speed = 115200

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
src_dir = examples/arduino_basic/src
lib_deps = symlink://.
monitor_speed = 115200